postgres:
  user: superuser
  password: superuser
  database: serapisdb
  port: 5432
Security:
  enable_rbac: 1
  login_with_username: 1
  login_with_email: 1
  jwt_algorithm: HS256
  jwt_ttl: 3600
  jwt_base_secret : dev-secret-from-configfile
  jwt_base_secret_storage : vault
  jwt_base_secret_filename : secret.key1
  jwt_base_secret_vault_storage_name : kv_test
  jwt_base_secret_vault_secret_name : jwt